### ISSUE TITLE
Question 2 explanation might be incorrect

### ISSUE THREAD

**Issue by domdrag** [knatten/cppquiz#249]
The explanation states that we would have a temporary std::string created if we called the the first function with string literal as the argument. I believe this is not correct since temporary objects should not be created when binding reference to a non-prvalue expression and since string literal is a lvalue expression.

Here's the link to the question and explanation of the answer: https://cppquiz.org/quiz/question/2?result=OK&answer=22&did_answer=Answer

Apologies if I'm in wrong and for taking your time.

**Comment by knatten** [comment]
Hi, and thanks for reporting an issue! I'm always happy that people post their concerns. In this case, I think the explanation is correct though. It's the second question ever created on the site, from before I started to add references to the standard all over, so it's not as good as most of the newer explanations. But I still think it is correct.

> I believe this is not correct since temporary objects should not be created when binding reference to a non-prvalue expression and since string literal is a lvalue expression.

The `std::string` reference in `void f(const std::string &)` has to bind to a `std::string` or a `std::string&`. It can not bind to a string literal, which is of a completely different type. So the only way for it to be able to bind to `"foo"` or `bar` is to first convert the string literal to an actual `std::string`, and then bind the reference to that new string.

I don't have time to give a full explanation now with references to the standard, but you can see a demonstration here of what happens if we comment out the second overload and force it to pick the first one: https://godbolt.org/z/1onE534GK. You can see that it calls the `std::string` constructor, or more specifically:

```c++
call    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&)
```

What do you think, do you agree with my reasoning?

**Comment by knatten** [comment]
Cool, then I'll close this.
