### ISSUE TITLE
Explanation for the Question #259 might be incorrect

### ISSUE THREAD

**Issue by komurugov** [knatten/cppquiz#253]
Hi there,
First of all let me say thanks for this very interesting and useful quiz!

In the Question #259 this part of code
```
int main() {
    char x = 1;
    char y = 2;
    f(x + y);
}
```
has following explanation:

> So both chars go through integral promotions. Those are defined in [§[conv.prom]¶1](https://timsong-cpp.github.io/cppwp/n4659/conv.prom#1):
A prvalue of an integer type other than bool, char16_t, char32_t, or wchar_t whose integer conversion rank (7.15) is less than the rank of int can be converted to a prvalue of type int if int can represent all the values of the source type; otherwise, the source prvalue can be converted to a prvalue of type unsigned int.

But it seems to be irrelevant to **x** and **y** since they aren't prvalues, are they?

**Comment by knatten** [comment]
Good question! It's because lvalues are typically converted to rvalues before they change type. For instance, a standard conversion sequence starts with the following before getting to the "actual" conversions: [§conv¶1.1](https://timsong-cpp.github.io/cppwp/n4659/conv#1.1):
> Zero or one conversion from the following set: lvalue-to-rvalue conversion, array-to-pointer conversion, and function-to-pointer conversion.


The same applies for the usual arithmetic conversions. Shortly before [§expr¶11](https://timsong-cpp.github.io/cppwp/n4659/expr#11) which I quote in the explanation, we find [§expr¶9](https://timsong-cpp.github.io/cppwp/n4659/expr9), which I didn't quote, but maybe should have for completeness:
> Whenever a glvalue expression appears as an operand of an operator that expects a prvalue for that operand, the [lvalue-to-rvalue](https://timsong-cpp.github.io/cppwp/n4659/conv.lval), [array-to-pointer](https://timsong-cpp.github.io/cppwp/n4659/conv.array), or [function-to-pointer](https://timsong-cpp.github.io/cppwp/n4659/conv.func) standard conversions are applied to convert the expression to a prvalue.

Maybe I should include this too in the explanation?
