### ISSUE TITLE
Missing questions: Were they retracted?

### ISSUE THREAD

**Issue by raavimohindar** [knatten/cppquiz#256]
[C++Quiz.xlsx](https://github.com/knatten/cppquiz/files/9442875/C%2B%2BQuiz.xlsx)

Prepared an excel sheet to sort out the questions according to the difficulty and it came all good. 

My question is what happened to those questions which are marked gray in the excel sheet. Are they retracted for any reasons? 

If possible, can you make them available either online/offline?

**Comment by knatten** [comment]
Question IDs are just the primary key in the database, they don't have any semantics other than that. So the grey ones could be for instance:
- Questions that are not done yet, e.g. just me typing in an idea like "Note to self: Make a question about partial ordering"
- Spam that a bot filled in in the submission form (The long series from 53 to 104 were mostly that iirc)
- Submitted questions that are plain wrong (I do get some of these where people just tested stuff on their machine and the behaviour is not actually guaranteed by the standard)
- Submitted questions that are uninteresting (I e.g. got one submission which just went `int main() { std::cout << "Hello World";}`
- Questions that have been retracted due to a non-fixable problem being discovered after publishing (has happened 3 times)

And so on. So the question IDs can not actually be used for anything interesting.
