### ISSUE TITLE
Question #127

### ISSUE THREAD

**Issue by denghe** [knatten/cppquiz#313]
msvc  gcc  output  01000, clang output 00100

**Comment by tocic** [comment]
Please look for the duplicates first: #96, #106, #110, #146, #150, #243.

**Comment by knatten** [comment]
This is also explained in the explanation to the question:

> 
Note that due to [this gcc issue ](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63192) (see also [this gcc issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66672) and [this cppquiz issue](https://github.com/knatten/cppquiz/issues/96) ), gcc erroneously outputs `01000` instead.
