### ISSUE TITLE
Question 244 seems to have incorrect answer

### ISSUE THREAD

**Issue by VishalSubramanyam** [knatten/cppquiz#322]
The following is taken from [cppreference - static_assert](https://en.cppreference.com/w/cpp/language/static_assert)

> A static_assert declaration may appear at namespace and block scope (as a [block declaration](https://en.cppreference.com/w/cpp/language/declarations)) and inside a class body (as a [member declaration](https://en.cppreference.com/w/cpp/language/class)).
> 
> If bool-constexpr is well-formed and evaluates to true, or is evaluated in the context of a template definition and the template is uninstantiated, this declaration has no effect. **Otherwise a compile-time error is issued**, and the text of message, if any, is included in the diagnostic message.

So a compile-time error is expected.

**Comment by tocic** [comment]
Please see [the explanation of the answer](https://cppquiz.org/quiz/question/244?result=UD&answer=&did_answer=Answer) and [this paragraph](https://timsong-cpp.github.io/cppwp/std20/temp#res.general-8.4) from the draft. Your link describes the behaviour of the `static_assert` declaration alone, but the issue here is in the usage of a class template with such a declaration.
