### ISSUE TITLE
Problem with question 286

### ISSUE THREAD

**Issue by Nathan-M-code** [knatten/cppquiz#374]
[ref](https://cppquiz.org/quiz/question/286)
I don't understand why the answer is undefined behavior.
At the end of the answer:

```
Note:

One could imagine systems where this wouldn't cause undefined behavior.
- If you have 64 bit ints, you don't get overflow.
- If short and int both are 32 bits, all values of unsigned short can't fit in an int, and they promote to unsigned int instead, for which overflow isn't undefined behavior.
```

Is it the exact definition of 'implementation defined' ?
The result - UB or not - is defined by the implementation.

**Comment by knatten** [comment]
For something to be implementation defined, the standard must require all implementations to define what the result will be. This result must be a concrete result, no implementation can be allowed to specify it as "undefined behavior". Similarly, for unspecified behavior, the result must be something sensible, even if the implementation is not required to specify exactly what the result is.

Since the standard allows implementations to have undefined behavior (signed integer arithmetic overflow) for this question, it can't require the behavior to be implementation defined.

Implementation defined and unspecified behavior is actually nice, your program can contain these and work just fine. E.g. you know that evaluations of function arguments happen before the function is called, just not in which order they're evaluated. Or you don't know the size of `int`, but that's fine. If implementations were allowed to define some implementation defined behaviors to be UB, suddenly you must assume all implementation defined behavior in your program could turn into undefined behavior on some implementation. And now you can no longer have implementation defined behavior in your program and have it be well formed portable C++.

**Comment by Nathan-M-code** [comment]
Thank you for this clarification :)
