### ISSUE TITLE
The explanation of the answer for Question 17 is wrong

### ISSUE THREAD

**Issue by justinjdickow** [knatten/cppquiz#4]
It says:
The base class constructor is called before the inherited constructor. The inherited constructor is called before the base class constructor.

It should say:
The base class constructor is called before the inherited constructor. The inherited destructor is called before the base class destructor.

**Comment by bogiord** [comment]
There are no inherited constructors in the example. Changing "inherited constructor" to "derived class constructor" would be better, I think, but still not strictly correct. According to [\[class.base.init\]/13](http://eel.is/c++draft/class.base.init#13), the initialization of bases is part of the execution of a derived class constructor, not something that happens before it. I guess a strict wording could be:

  - The base class is initialized (by calling its constructor) before the *compound-statement* of the derived class constructor body is executed.

or (this sounds better to me - it emphasizes who's in control): 

  - The derived class constructor first calls the base class constructor, and then executes the *compound-statement* of its own body.

(The body of the constructor includes the *ctor-initializer*, hence *compound-statement* to strictly specify what gets executed.)

Also, "inherited destructor" -> "derived class destructor", but see [\[class.dtor\]/9](http://eel.is/c++draft/class.dtor#9) - it's the same problem. I'd say:

  - The body of the derived class destructor is executed before the base class destructor.

or 

  - The derived class destructor first executes its own body, and then calls the base class destructor.

(The quotes are from the latest draft, but the paragraphs haven't changed since C++11, except for a tiny correction for destructors.)

**Comment by knatten** [comment]
Thanks for those clarifications @bogiord! I've updated the answer now with your suggested wording, plus some references to the standard: http://cppquiz.org/quiz/question/17?result=OK&answer=abBA&did_answer=Answer
