### ISSUE TITLE
Slight issue with the explanation for the answer to question #163

### ISSUE THREAD

**Issue by bogiord** [knatten/cppquiz#72]
The second paragraph in the explanation references a standard quote that is not relevant to the example. `P` is not a reference type in this case; it would be if the declaration were something like `auto& bar`.

In our case, `P` is something like `T`, where `T` would be a template parameter of an invented function template, and `A` is the type of the expression `a.getFoo()`, which is initially `int&` but is immediately adjusted to `int` according to [expr]/5: 

> If an expression initially has the type “reference to T” (11.3.2, 11.6.3), the type is adjusted to T prior to any further analysis. [...]

**Comment by knatten** [comment]
Thanks for filing an issue, this looks like something I should have caught in review. Let me just check that I've understood the issue correctly:

According to §7.1.6.4¶6 in the C++11 standard (the one cpquiz.org still uses, I have to update that at some point):

> Let T be the type that has been determined for a variable identifier d. Obtain P from T by replacing the occurrences of auto with (...) a new invented type template parameter U. The type deduced for the variable d is then the deduced A determined using the rules of template argument deduction from a function call (14.8.2.1), where P is a function template parameter type and the initializer for d is the corresponding argument. 

The confusion in the original answer here seems to be between `P` and `A`, where `A` is the type of `a.getFoo()`, but `P` is the template parameter type. So `P` never has anything to do with references, it's `a.getFoo()` which is of a  reference type. 

This makes `P` very simple, and none of the points in 14.8.2.1 are very interesting, only that "the deduction process attempts to find template argument values that will make the deduced A identical to A". 

Then, §5¶5 applies before the deduction, turning `int&` into `int`, which leads to the type of the *argument* `A` being `int`, which leads to the type of the *deduced* `A` being `int`, which leads to the type of `bar` being `int`.

That was a bit long winded, but I wanted to make sure I understood all details. If you agree with my reasoning here, I'll try to condense that a bit and update the answer to the question.

For reference, here's the original answer:

> According to §7.1.7.4¶4 the type of a variable declared using auto is deduced from its initializer using the rules for template argument deduction (§14.8.2.1).
As stated in §14.8.2.1¶3, if P is a reference type, ***the type referred to by P*** is used for type deduction.
> 
> Applied to our case, this means that although `getFoo()` returns `int&`, the type deduced by `auto` is `int`. Incrementing `bar` doesn't change the value of `A::foo`.
>
> Result: 0.

**Comment by bogiord** [comment]
Yup, that's how it works.

If you want to make it a bit more interesting, you could change the return type of `getFoo` to `const int&`. The result will be the same, but some people may be tempted to say it's a compile error, if they wrongly assume that the type of `bar` will be deduced to `const int`. It's not; it's still `int`, because of [temp.deduct.call]/2.3:

>  If `P` is not a reference type: [...] If `A` is a cv-qualiﬁed type, the top-level cv-qualiﬁers of `A`’s type are ignored for type deduction.

I'm not sure if it makes sense to complicate the question (and the explanation) with this; I'll leave that decision to you.

**Comment by knatten** [comment]
Below is an updated answer. I'll run this by the original author of the question as well, to get his/her input on it.

---


To get to the bottom of this, we need to take a detour via template functions.

According to §7.1.6.4¶6 (`auto` specifier) in the standard:
"The type deduced for the variable [is] determined using the rules of template argument deduction from a function call (14.8.2.1)"

So the rules for `auto bar = a.getFoo();` are the same as if we did
```
template<typename T> void f(T t);
f(a.getFoo());
```

Let's have a look at §14.8.2.1¶4:
"In general, the deduction process attempts to find template argument values that will make the deduced `A` identical to `A`" (where `A` is the type of the argument of the call.)

Now what is the type of the argument of the call? `getFoo()` returns `int&`, but let's see what §5¶5 has to say about the type of expressions:
"If an expression initially has the type “reference to `T`”, the type is adjusted to `T` prior to any further analysis."

So the type of _the expression_ `a.getFoo()` is `int`, not `int&`. Now `int` is being used for deducing `T` in our imaginary void `f(T t)`, so `T` is `int`. Since `auto` uses the same rule, the type of `bar` is also `int`.

Since `bar` is not a reference, incrementing it does not increment `foo`, and the output of the program is `0`.

**Comment by bogiord** [comment]
Excellent explanation.

Ridiculously minor nitpicking (you really can leave everything as is, it's great):

- In the first paragraph, "template functions" -> "function templates".
- In the second to last paragraph, "the type of the expression" -> "the adjusted type of the expression", or "the type of the expression `a.getFoo()` that is used for deduction" - to avoid the interminable debate over whether "an expression is ever of a reference type" ([expr.call]/3 says *[...] the type of the function call expression is the return type of the statically chosen function [...]* so arguably it is initially a reference type but immediately adjusted).

**Comment by knatten** [comment]
Thanks for the nitpicking! The goal of CppQuiz is to be as correct as possible, so I think these things are important. I've updated the answer now.
