### ISSUE TITLE
Wrong answer in question 127

### ISSUE THREAD

**Issue by messi1** [knatten/cppquiz#96]
Hi
When I tested the question 127 with wandbox.org and various compilers with C++11 mode,
I always receive as result 01000.

But your answer is 00100.

Can you verify this behaviour?

 g++ prog.cc -Wall -Wextra -std=c++11

```
#include <iostream>
#include <type_traits>

using namespace std;

int main()
{
  int i, &j = i;
  [=]
  {
    cout << is_same<decltype    ((j)),     int         >::value
         << is_same<decltype   (((j))),    int      &  >::value
         << is_same<decltype  ((((j)))),   int const&  >::value
         << is_same<decltype (((((j))))),  int      && >::value
         << is_same<decltype((((((j)))))), int const&& >::value;
  }();
}
```

**Comment by knatten** [comment]
Thanks for reporting! Clang gives me `00100`, so one of them is wrong according to C++11.

This question was contributed by a user four years ago, so I don't remember all the details here, but reading the standard now I think I have an idea of what's going on.

First of all, I think the [explanation](http://cppquiz.org/quiz/question/127?preview_key=awrgawta4a) is a bit wrong, as it claims that `j` is captured by copy. But according to the example in §5.1.2¶18, appearance in a decltype operand is not an odr-use, so I don't think `j` is actually captured at all. However, §5.1.2¶18 notes that `decltype((j))` still is treated as if it _was_ captured, so this shouldn't affect the outcome of the program. I suggest changing the answer to be more precise though.

As for the output, it looks like gcc and clang at least agrees that `j` is an lvalue reference, but they disagree on whether it is const.

I created this example to demonstrate what I believe should be happening under the hood here:

```cpp
#include <iostream>
using namespace std;

struct C {
    int j;

    void operator()() const {
        cout << is_same<decltype   (((j))),    int      &  >::value
             << is_same<decltype  ((((j)))),   int const&  >::value;
    }
};

int main() {
    C c;
    c();
}
```

And both gcc and clang agree to print `01` here, which is what clang also does for the question. If I remove `const` on `operator()`, they both agree on printing `10`. 

So it looks like gcc under the hood creates a non-const `operator()`, whereas clang creates a const `operator()`. And according to 5.1.2¶5, I think clang is correct:
> The closure type for a lambda-expression has a public inline function call operator (13.5.4) whose param- eters and return type are described by the lambda-expression’s parameter-declaration-clause and trailing- return-type respectively. This function call operator is declared const (9.3.1) if and only if the lambda- expression’s parameter-declaration-clause is not followed by mutable. 

After clearing up all of this, I decided to see if a bug had been opened against gcc for this, and I found [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66672), which actually talks about this very question on cppquiz.org! In that thread, Lukas refers to [capture-11.sentence-3](http://eel.is/c++draft/expr.prim.lambda#capture-11.sentence-3) to defend the behavior of gcc. I notice that in that version of the standard, the entire section §5.1.2¶18 from C++11 is gone.

So to conclude, I think Clang is correct according to C++11, and GCC is correct according to whichever standard first contained the changes we see in [capture-11.sentence-3](http://eel.is/c++draft/expr.prim.lambda#capture-11.sentence-3).

Since cppquiz.org uses the C++11 standard, cppquiz.org is currently correct. I've made a note to update this question when porting cppquiz to C++17.

**Comment by messi1** [comment]
Hi Anders
Thanks a lot for the detailed explanation and for finding the gcc bug.
I can live for now that gcc is right with greater than C++1x and clang is right with C++11
But when clang is wrong with C++1x and C++2x we should file a bug similar to the one in the gcc bug list.

**Comment by knatten** [comment]
Actually, after reading [Richard's reply](https://bugs.llvm.org/show_bug.cgi?id=35423#c2) to Lukas' bug report, I think that Clang is still correct, even with newer versions of the standard. I was not aware of [expr.prim.id.unqual#2.sentence-2](http://eel.is/c++draft/expr.prim.id.unqual#2.sentence-2), which seems to cover the same case that was previously covered by §5.1.2¶18. It says:

> If the entity is a local entity and naming it from outside of an unevaluated operand within the declarative region where the unqualified-id appears would result in some intervening lambda-expression capturing it by copy ([expr.prim.lambda.capture]), the type of the expression is the type of a class member access expression ([expr.ref]) naming the non-static data member that would be declared for such a capture in the closure object of the innermost such intervening lambda-expression. 

This is as far as I can tell another way of saying "`decltype` doesn't odr-use the identifier, so it isn't actually captured, but still the type of the expression is as _if it had been_ captured."

**Comment by knatten** [comment]
Unless anyone objects, I'm going to close this issue based on the assumption that cppquiz and clang are correct, and gcc is wrong.

**Comment by guptashiv** [comment]
Hi,

Sorry for bugging this thread after 2 years!
but now when the page clearly says **"According to the C++17 standard, what is the output of this program?"**

It still reports 00100 as the correct answer:https://cppquiz.org/quiz/question/127?result=OK&answer=00100&did_answer=Answer

**Comment by messi1** [comment]
Hi guptashiv
It is a problem in the missunderstanding of the C++ standard.
With Clang 13 it returns 00100
With GCC it returns 01000

So it seems that gcc is still doing it wrong.
GCC was handling it correct with the C++11 standard.
But clang is doing it correct with C++14 and higher.
Please read the standard §5.1.2¶18
Then you will realize that gcc is still doing it wrong.
With have reported the bugs but nobody cares about it.
Best regards
Juergen

**Comment by knatten** [comment]
I have not seen anything that suggests that the question is wrong after we moved to C++17, I rather think that GCC is still wrong and Clang still right. Do you have any particular reason to believe otherwise, @guptashiv?

> Can we fix this?

Fix what exactly, and with which justification?

**Comment by guptashiv** [comment]
@messi1  Thanks for the explanation. 

@knatten apologies for my negligence. You are right, the answer is correct as per the standards.
godbolt's clang adheres to the standard as mentioned and results in correct output.

**Comment by knatten** [comment]
> @messi1 Thanks for the explanation.
> 
> @knatten apologies for my negligence. You are right, the answer is correct as per the standards. godbolt's clang adheres to the standard as mentioned and results in correct output.

No apologies needed! These kinds of questions are very important. Just a few days ago I retracted a question which I was sure I had got right, but someone found a problem with.
